name: Continuous Integration Pipeline

on: push

jobs:
  test:
    name: Black Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lgeiger/black-action@master
        with:
          args: .