name: Continuous Integration Pipeline

on: push

jobs:
  test:
    name: Black Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: RojerGS/python-black-check@master
        with:
          line-length: '130'
          path: 'backend/resources'